sudo: required
language: node_js
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com/ | sh
- npm install -g mup

- openssl aes-256-cbc -K $encrypted_0c1af61c99ea_key -iv $encrypted_0c1af61c99ea_iv
  -in settings.tar.enc -out settings.tar -d
- tar xvf settings.tar
services: mongodb
script:
- meteor --test --settings settings.json --release velocity:METEOR@1.1.0.2_3
after_success:
- curl -L http://git.io/vqbln | sh
